### ISSUE TITLE
无法解析http://v.youku.com/v_show/id_XMjcxMjI2MDYwMA==.html?qq-pf-to=pcqq.temporaryc2c

### ISSUE THREAD

**Issue by redstoneleo** [AnoyiX/anoyi#1]
大哥你的这个项目太强大~\(≧▽≦)/~啦啦啦
但是我试了下不能解析http://www.ictgu.cn/play?v=http://v.youku.com/v_show/id_XMjcxMjI2MDYwMA==.html?qq-pf-to=pcqq.temporaryc2c
能解决吗？

**Comment by AnoyiX** [comment]
优酷的已经修复，支持优酷VIP视频的解析。
优酷视频的播放不能使用Chrome内核的浏览器，你可以使用Windows自带的Edge浏览或者手机浏览器来观看优酷视频。

**Comment by redstoneleo** [comment]
这个链接依然没结果 http://www.ictgu.cn/play?v=http://v.youku.com/v_show/id_XMjcxMjI2MDYwMA==.html?qq-pf-to=pcqq.temporaryc2c

**Comment by redstoneleo** [comment]
很遗憾，Chrome这么先进的浏览器都看不了

**Comment by AnoyiX** [comment]
Chrome的H5播放器不支持，没办法

**Comment by redstoneleo** [comment]
你是说H5的<video>标签无法播放flv或MP4吗？
这里说可以解决这个问题，https://github.com/nareix/mama-hd#原理
该项目貌似现在活跃于https://github.com/zythum/mama2/

**Comment by AnoyiX** [comment]
你有兴趣来处理这个问题吗？

**Comment by redstoneleo** [comment]
目前暂时不，其实换个CKPLayer就可以避免很多折腾了

**Comment by AnoyiX** [comment]
坚决不用flash
