### ISSUE TITLE
在下有几个问题？ 

### ISSUE THREAD

**Issue by cccvip** [AnoyiX/anoyi#14]
1 （Tips:可以忽视）我是在SpringCloud看到您的这篇文章的，但是您用的框架并未过多关于SpringCloud的东西，有点奇怪。
2 感兴趣的部分  爬虫部分 以及redis缓存（使用集群吗？） 
3 原谅我并没有过多的看您的代码，粗浅的提出我的疑问

**Comment by AnoyiX** [comment]
1、线上使用 Spring Cloud 需要服务器支持才能用得起来，现在本项目的功能点，使用单个 Spring Boot 应用已经够了。
2、爬虫代码在 parse 和 job 路径， redis 缓存没有使用集群，由于线上服务器限制

**Comment by cccvip** [comment]
所有应用Service的地方，都出现未被初始化的问题。 这个因为jdk版本不一样导致的吗？

**Comment by AnoyiX** [comment]
看下这篇文章，http://www.jianshu.com/p/dd5349ac8473   ，里面介绍了 Lombok 简化代码
