### ISSUE TITLE
关于版权问题是如何处理的

### ISSUE THREAD

**Issue by firejq** [AnoyiX/anoyi#15]
这种聚合平台难免会涉及版权问题，请问作者是如何处理的

**Comment by AnoyiX** [comment]
演示网站下方有写：“本站资源来源于互联网解析，仅供学习参考，请勿用于商业用途，违者必究！”，本项目纯属技术交流，非商用，视频官方有人联系我们的话，我们会按要求移除内容

**Comment by firejq** [comment]
好的 谢谢 :)
