### ISSUE TITLE
程序启动后页面不能正常访问

### ISSUE THREAD

**Issue by icnz** [AnoyiX/anoyi#30]
非常感谢能够分享springboot相关的技术。
git程序后，程序正常启动，但是访问web首页时，页面不能正常显示，接连出了好几个错误：
主要是对THYMELEAF还没有理解，有些问题不会解决。
1、没有结束标签问题，已解决。
     比如：&lt;meta charset="utf-8"&gt;，需要加一个结束符&lt;meta charset="utf-8"/&gt;
2、标签里属性没有写=，已解决。
     比如：<script async，需要写为<script async=“async” 
3、未解决：
     org.xml.sax.SAXParseException: 与元素类型 "null" 相关联的 "th:class" 属性值不能包含 '<' 字符。
     问题在：
     &lt;div th:class="${iterStat.index} &lt; 12 ? 'column videoItem' : 'videoItem'" th:each="recommend, iterStat:${recommends}"&gt;
4、未解决：
     org.xml.sax.SAXParseException: 元素类型 "link" 必须由匹配的结束标记 "</link>" 终止。
     问题分析：
     是在解析其他网站的html时出的问题？本地页面对上述问题已经修改了。

上述问题为什么会出现呢，是因为默认是严格模式？问题3是语法问题？
但是你的程序没有问题。
该如何解决？

**Comment by AnoyiX** [comment]
请参考部署文档进行使用
