### ISSUE TITLE
CONFIG

### ISSUE THREAD

**Issue by fxgurv** [AnoyiX/anoyi#37]
is there any manual that i can read and get the env values from mongodb? 
i am unable to find the options you have specified like 

MONGODB_API
MONGODB_API_KEY
MONGODB_DATASOURCE
NEXT_PUBLIC_GA_MEASUREMENT_ID

all the variables looks same and its confusing me

**Comment by AnoyiX** [comment]
MongoDB data API is deprecated, I will change it to another database, or use mongo client sdk to connect mongodb.

**Comment by fxgurv** [comment]
YOU MEAN SOMETHING LIKE THIS ? 


mongodb+srv://ason:<db_password>@bXXXXz.mXXXXcyn.mongodb.net/?retryWrites=true&w=majority&appName=XYZ

**Comment by AnoyiX** [comment]
![image](https://github.com/user-attachments/assets/75e9ca90-d6e1-4a3c-a0ea-f6729e180fcb)

example env config
```
MONGODB_API=https://data.mongodb-api.com/app/data-ludyh/endpoint/data/v1
MONGODB_API_KEY=***************************************************************
MONGODB_DATASOURCE=AnoyiCluster
```

**Comment by fxgurv** [comment]
Awesome! Thank you !

**Comment by fxgurv** [comment]
ahhhhhhhh i am unable to find this data api option....

**Comment by AnoyiX** [comment]
using MongoDB SDK would be better than MongoDB API, i will update it in the next few days

**Comment by fxgurv** [comment]
will wait for the update then :)

**Comment by AnoyiX** [comment]
hi, it has been updated. now, you can set a environment variable `MONGO_URI` to connect your database.
