### ISSUE TITLE
老大，我又来了

### ISSUE THREAD

**Issue by chenzhijun** [AnoyiX/anoyi#4]
上次跑你的项目，对springboot 不是很了解。所以回去学习了一下，平常工作抽了点时间。 

org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Undertow

想请教下。 Undertow, 我是要做什么配置么?

**Comment by AnoyiX** [comment]
建议先写个小demo，实现用Undertow来启动spring boot应用

**Comment by chenzhijun** [comment]
我还停留在tomcat上,手动捂脸.png

**Comment by AnoyiX** [comment]
手动写下，代码量很少

**Comment by chenzhijun** [comment]
下班回家搞起来了。 80端口改成8085。 不得不说。 真的强大。 基本上就是clone下来，直接可以跑起来。

**Comment by AnoyiX** [comment]
嗯，可以贡献代码哦，我最近准备以企业级代码标准把项目重构下
