### ISSUE TITLE
出错了

### ISSUE THREAD

**Issue by redstoneleo** [AnoyiX/anoyi#5]
http://www.ictgu.cn/play?v=http://www.iqiyi.com/v_19rro7upa0.html?vfm=2008_aldbd&fc=828fb30b722f3164&fv=p_02_01
看不了爱奇艺吗？优酷貌似也不行
显示
ERROR

**Comment by AnoyiX** [comment]
新代码，已经移除了对爱奇艺和优酷的支持，你们可以贡献代码哦
